def mobina():
        x=int(input("enter saat kari =  "))
        y=40
        p=x-160
        if x>=160 :
                if y>=x-160 :
                        m=160*100000
                        s=p*50000
                        kol=m+s
                        print(f"kol hoghgh shoma ba {p} saat ezafe kari = {kol} hast")
        elif x<160 :
                m=x*100000
                print(f"hoghgh shoma bdone ezafe kari {m} hast ")
        else :
                print("error") 
mobina()  



